#include "cuda.h"
#include "metal.h"

CUresult cuDriverGetVersion(int* driverVersion) {
  static const auto major = 12;
  static const auto minor = 0;
  static const auto version = major * 1000 + minor * 10;
  if (!driverVersion) {
    return CUDA_ERROR_INVALID_VALUE;
  }

  *driverVersion = version;
  return CUDA_SUCCESS;
}

CUresult cuInit(unsigned int flags) {
  return CUDA_SUCCESS;
}

static auto cuErrorName(CUresult error) -> const char* {
#define X(name) \
  case name: return #name;
  switch (error) {
    X(CUDA_SUCCESS);

    // Invalid input
    X(CUDA_ERROR_INVALID_VALUE);

    // Memory allocation errors
    X(CUDA_ERROR_OUT_OF_MEMORY);

    // Initialization errors
    X(CUDA_ERROR_NOT_INITIALIZED);
    X(CUDA_ERROR_DEINITIALIZED);

    // Profiler errors
    X(CUDA_ERROR_PROFILER_DISABLED);
    X(CUDA_ERROR_PROFILER_NOT_INITIALIZED);
    X(CUDA_ERROR_PROFILER_ALREADY_STARTED);
    X(CUDA_ERROR_PROFILER_ALREADY_STOPPED);

    // Driver errors
    X(CUDA_ERROR_STUB_LIBRARY);
    X(CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER);
    X(CUDA_ERROR_DEVICE_UNAVAILABLE);

    // Device errors
    X(CUDA_ERROR_NO_DEVICE);
    X(CUDA_ERROR_INVALID_DEVICE);
    X(CUDA_ERROR_DEVICE_NOT_LICENSED);

    // Image/Module errors
    X(CUDA_ERROR_INVALID_IMAGE);
    X(CUDA_ERROR_INVALID_CONTEXT);
    X(CUDA_ERROR_CONTEXT_ALREADY_CURRENT);

    // Memory mapping errors
    X(CUDA_ERROR_MAP_FAILED);
    X(CUDA_ERROR_UNMAP_FAILED);
    X(CUDA_ERROR_ARRAY_IS_MAPPED);
    X(CUDA_ERROR_ALREADY_MAPPED);
    X(CUDA_ERROR_NO_BINARY_FOR_GPU);
    X(CUDA_ERROR_ALREADY_ACQUIRED);
    X(CUDA_ERROR_NOT_MAPPED);
    X(CUDA_ERROR_NOT_MAPPED_AS_ARRAY);
    X(CUDA_ERROR_NOT_MAPPED_AS_POINTER);

    // ECC and hardware errors
    X(CUDA_ERROR_ECC_UNCORRECTABLE);
    X(CUDA_ERROR_UNSUPPORTED_LIMIT);
    X(CUDA_ERROR_CONTEXT_ALREADY_IN_USE);
    X(CUDA_ERROR_PEER_ACCESS_UNSUPPORTED);

    // PTX/JIT compilation errors
    X(CUDA_ERROR_INVALID_PTX);
    X(CUDA_ERROR_INVALID_GRAPHICS_CONTEXT);
    X(CUDA_ERROR_NVLINK_UNCORRECTABLE);
    X(CUDA_ERROR_JIT_COMPILER_NOT_FOUND);
    X(CUDA_ERROR_UNSUPPORTED_PTX_VERSION);
    X(CUDA_ERROR_JIT_COMPILATION_DISABLED);
    X(CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY);
    X(CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC);
    X(CUDA_ERROR_CONTAINED);

    // Source/Compilation errors
    X(CUDA_ERROR_INVALID_SOURCE);
    X(CUDA_ERROR_FILE_NOT_FOUND);
    X(CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND);
    X(CUDA_ERROR_SHARED_OBJECT_INIT_FAILED);
    X(CUDA_ERROR_OPERATING_SYSTEM);

    // Handle errors
    X(CUDA_ERROR_INVALID_HANDLE);
    X(CUDA_ERROR_ILLEGAL_STATE);
    X(CUDA_ERROR_LOSSY_QUERY);

    // Symbol errors
    X(CUDA_ERROR_NOT_FOUND);
    // Async errors
    X(CUDA_ERROR_NOT_READY);

    // Launch errors
    X(CUDA_ERROR_ILLEGAL_ADDRESS);
    X(CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES);
    X(CUDA_ERROR_LAUNCH_TIMEOUT);
    X(CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING);

    // Peer access errors
    X(CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED);
    X(CUDA_ERROR_PEER_ACCESS_NOT_ENABLED);

    // Context errors
    X(CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE);
    X(CUDA_ERROR_CONTEXT_IS_DESTROYED);
    X(CUDA_ERROR_ASSERT);

    // Resource errors
    X(CUDA_ERROR_TOO_MANY_PEERS);
    X(CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED);
    X(CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED);

    // Hardware errors
    X(CUDA_ERROR_HARDWARE_STACK_ERROR);
    X(CUDA_ERROR_ILLEGAL_INSTRUCTION);
    X(CUDA_ERROR_MISALIGNED_ADDRESS);
    X(CUDA_ERROR_INVALID_ADDRESS_SPACE);
    X(CUDA_ERROR_INVALID_PC);
    X(CUDA_ERROR_LAUNCH_FAILED);
    X(CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE);
    X(CUDA_ERROR_TENSOR_MEMORY_LEAK);

    // System errors
    X(CUDA_ERROR_NOT_PERMITTED);
    X(CUDA_ERROR_NOT_SUPPORTED);
    X(CUDA_ERROR_SYSTEM_NOT_READY);
    X(CUDA_ERROR_SYSTEM_DRIVER_MISMATCH);
    X(CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE);

    // MPS errors
    X(CUDA_ERROR_MPS_CONNECTION_FAILED);
    X(CUDA_ERROR_MPS_RPC_FAILURE);
    X(CUDA_ERROR_MPS_SERVER_NOT_READY);
    X(CUDA_ERROR_MPS_MAX_CLIENTS_REACHED);
    X(CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED);
    X(CUDA_ERROR_MPS_CLIENT_TERMINATED);

    // CDP errors
    X(CUDA_ERROR_CDP_NOT_SUPPORTED);
    X(CUDA_ERROR_CDP_VERSION_MISMATCH);

    // Stream capture errors
    X(CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED);
    X(CUDA_ERROR_STREAM_CAPTURE_INVALIDATED);
    X(CUDA_ERROR_STREAM_CAPTURE_MERGE);
    X(CUDA_ERROR_STREAM_CAPTURE_UNMATCHED);
    X(CUDA_ERROR_STREAM_CAPTURE_UNJOINED);
    X(CUDA_ERROR_STREAM_CAPTURE_ISOLATION);
    X(CUDA_ERROR_STREAM_CAPTURE_IMPLICIT);
    X(CUDA_ERROR_CAPTURED_EVENT);
    X(CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD);

    // Timeout and graph errors
    X(CUDA_ERROR_TIMEOUT);
    X(CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE);

    // External errors
    X(CUDA_ERROR_EXTERNAL_DEVICE);
    X(CUDA_ERROR_INVALID_CLUSTER_SIZE);
    X(CUDA_ERROR_FUNCTION_NOT_LOADED);
    X(CUDA_ERROR_INVALID_RESOURCE_TYPE);
    X(CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION);
    X(CUDA_ERROR_KEY_ROTATION);
    X(CUDA_ERROR_STREAM_DETACHED);

    // Unknown error
    default: return "CUDA_ERROR_UNKNOWN";
  }
#undef X
}

CUresult cuGetErrorName(CUresult error, const char** pStr) {
  if (!pStr) {
    return CUDA_ERROR_INVALID_VALUE;
  }
  *pStr = cuErrorName(error);
  return CUDA_SUCCESS;
}

CUresult cuGetErrorString(CUresult error, const char** pStr) {
  if (!pStr) {
    return CUDA_ERROR_INVALID_VALUE;
  }
  *pStr = cuErrorName(error);
  return CUDA_SUCCESS;
}
